### ISSUE TITLE
Bug in HS

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#110]
With a fresh install of HS from github I have this error :+1: 
```
# Generating new position and neighbor files from data file
Traceback (most recent call last):
  File "test_herdingspikes.py", line 17, in <module>
    HerdingspikesSorterCommonTestSuite().test_on_toy()
  File "/home/samuel/Documents/projet/spikeinterface/spiketoolkit/spiketoolkit/sorters/tests/common_tests.py", line 24, in test_on_toy
    sorter.run()
  File "/home/samuel/Documents/projet/spikeinterface/spiketoolkit/spiketoolkit/sorters/basesorter.py", line 92, in run
    self._run(recording, self.output_folders[i])
  File "/home/samuel/Documents/projet/spikeinterface/spiketoolkit/spiketoolkit/sorters/herdingspikes/herdingspikes.py", line 66, in _run
    H.DetectFromRaw(load=True, tInc=1000000)
  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/herdingspikes-0.3.0-py3.6-linux-x86_64.egg/herdingspikes/hs2.py", line 229, in DetectFromRaw
    tInc=tInc,
  File "herdingspikes/detection_localisation/detect.pyx", line 35, in herdingspikes.detection_localisation.detect.detectData
TypeError: detectData() takes at least 5 positional arguments (1 given)
```

**Comment by samuelgarcia** [comment]
Oups sorry.
I need to compile it again.
