### ISSUE TITLE
Probable problem between channel_id and channel_index in compute snr 

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#276]
Traceback (most recent call last):
  File "run_sorters_SF.py", line 471, in <module>
    collect_results()
  File "run_sorters_SF.py", line 219, in collect_results
    snr = study.get_units_snr()
  File "/home/samuel/Documents/Spikeinterface/spikecomparison/spikecomparison/groundtruthstudy.py", line 198, in get_units_snr
    snr = self._compute_snr(rec_name)
  File "/home/samuel/Documents/Spikeinterface/spikecomparison/spikecomparison/groundtruthstudy.py", line 175, in _compute_snr
    snr_list = st.validation.compute_snrs(gt_sorting, rec, unit_ids=None, save_as_property=False, **snr_kargs)
  File "/home/samuel/Documents/Spikeinterface/spiketoolkit/spiketoolkit/validation/quality_metrics.py", line 308, in compute_snrs
    save_features_props=save_features_props, seed=seed)
  File "/home/samuel/Documents/Spikeinterface/spiketoolkit/spiketoolkit/validation/metric_calculator.py", line 542, in compute_snrs
    max_channel_idx = epoch_recording.get_channel_ids().index(max_channels[i])
IndexError: invalid index to scalar variable.

**Comment by samuelgarcia** [comment]
get_unit_max_channels woaks with indexes
but
epoch_recording.get_channel_ids().index(max_channels[i])
play with ids

No ?

**Comment by samuelgarcia** [comment]
Note that this errors only occurs when a dataset have non continuous channel_ids like in the retina dataset from Pierre.

Could we make our test more robust against this ?
For instanace toy_dataset could have internal ids discontinuous.
With this I guess we should discover somes bugs here and here....
@alejoe91 @colehurwitz  : what do you think ?

**Comment by samuelgarcia** [comment]
My bad. get_unit_max_channels woaks with **ids** the bug is somewhere else.

**Comment by alejoe91** [comment]
@samuelgarcia can I close this?

**Comment by samuelgarcia** [comment]
I guess yes.
