### ISSUE TITLE
export_to_phy - TypeError: set_unit_spike_features() got an unexpected keyword argument 'indexes'

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#318]
I got this error if I set compute_pc_features as false:
Traceback (most recent call last):
  File "spikeinterface_class.py", line 291, in <module>
    si.run_ms(file_path, prb_file, ms4_params, numchan, sampling_frequency, 
  File "spikeinterface_class.py", line 97, in run_ms
    st.postprocessing.export_to_phy(recording_prb, sorting_MS4, 
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 992, in export_to_phy
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1414, in _get_phy_data
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1232, in _get_quality_metric_data
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 269, in get_unit_waveforms
TypeError: set_unit_spike_features() got an unexpected keyword argument 'indexes'

**Comment by alejoe91** [comment]
You should pull spikeextractors

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/issues/317#issuecomment-607172809

**Comment by alejoe91** [comment]
Then I'll make some final fixes and merge. Thanks again for helping for the tests :)
