### ISSUE TITLE
Cannot import spiketoolkit: No module named 'spikefeatures'

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#351]
Hi!

I updated spikeinterface to its later version, and now, when I do `import spiketoolkit as st` or `import spikeinterface.extractors as se`, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/__init__.py", line 1, in <module>
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/__init__.py", line 5, in <module>
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/features.py", line 7, in <module>
ModuleNotFoundError: No module named 'spikefeatures'
```

I tried uninstalling spikeinterface and installing it again, but the error persists.

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

the dependency was accidentally removed in the last commit (https://github.com/SpikeInterface/spiketoolkit/pull/352).

As the erro suggests, you are missing the `spikefeatures` package.
You can just `pip install spikefeatures` :)

**Comment by Dradeliomecus** [comment]
Thank you!

It now works :)
