### ISSUE TITLE
How to delete spikes in CurationSortingExtractor?

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#355]
Hi,

I am trying to remove certain spikes (similar to what I was doing in #339).
The solution of using the `CacheSortingExtractor` worked really well, and now I am trying to do the same but with the `CurationSortingExtractor`.
I successfully removed the spikes, but when doing the `export_to_phy()` method, I have the following error:
```
Traceback (most recent call last):
  File "remove_duplicated_spikes.py", line 24, in <module>
    st.postprocessing.export_to_phy(recording, sorting, output_folder=save_folder, verbose=True, n_jobs=1, ms_before=3, ms_after=4, compute_pc_features=False, max_spikes_per_unit=2000, recompute_info=False, memmap=True)
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1088, in export_to_phy
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1517, in _get_phy_data
  File "/home/aurelien/dev/miniconda3/envs/phy/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1429, in _get_quality_metric_data
ValueError: could not broadcast input array from shape (234166,1) into shape (234092,1)
```

From what I could gather, I think it has to do with the problem that I deleted the spikes but didn't update the amplitude array as well, which lead to a mismatch?

Here is how I deleted the spikes:
```
def del_spikes_from_unit(sorting, spikes, unit_id):
    if not isinstance(sorting, st.curation.CurationSortingExtractor):
        print("Converting sorting...")
        sorting = st.curation.CurationSortingExtractor(sorting)

    # Need to find the Unit in "roots" that matches our unit_id
    unit = "error"
    for root in sorting._roots:
        if root.unit_id == unit_id:
            unit = root
            break

    if unit == "error": # Didn't find the Unit with our unit_id
        print("Error in del_spikes_from_unit():")
        print("Unit ID {0} not found".format(unit_id))
        return

    spike_train = unit.get_spike_train()
    spike_train = np.delete(spike_train, spikes) # spikes is a numpy.ndarray containing indices of spikes to remove
    unit.set_spike_train(spike_train)

    return sorting
```

How should I use the `CurationSortingExtractor` to remove such spikes?
Thank you!

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

Can you try to run the `export_to_phy` with `recompute_info` set to `True`?
Also can you paste the entire code that you are using (from the recording-sorting definition to the export)?

**Comment by Dradeliomecus** [comment]
It's computing with `recompute_info = True`, but as our dataset is pretty big, it takes a while. I will let you know if the same error pops up.

Meanwhile, here is the code (split in 3 files):

In `./remove_duplicated_spikes.py`:
```
import spikeextractors as se
import spiketoolkit as st
from curation.remove_duplicates import remove_duplicates_from_sorting as remove_duplicates


phy_folder = "/home/aurelien/Documents/phy-7"
save_folder = "/home/aurelien/Documents/phy-7/test"
recording = se.PhyRecordingExtractor(phy_folder)
sorting = se.PhySortingExtractor(phy_folder)

sampling_rate = 30e3
window_duplicate = 400e-6 # A spike is considered a duplicate if there is another spike in the same unit less than 400 µs apart.
window_timepoints = round(window_duplicate * sampling_rate) # Convert to timepoints.


sorting = remove_duplicates(sorting, recording, window_duplicate=window_timepoints)

st.postprocessing.export_to_phy(recording, sorting, output_folder=save_folder, verbose=True, n_jobs=1, ms_before=3, ms_after=4, compute_pc_features=False, max_spikes_per_unit=2000, recompute_info=True, memmap=True)
```

In `curation/remove_duplicates.py`:
```
import os
import numpy as np
from curation.utils.sorting_utils import del_spikes_from_unit


def remove_duplicates_from_sorting(sorting, recording, window_duplicate=12):
    # For each unit, look at all spikes. If there is a spike
    # followed by another one with less than "window_duplicate" timepoints,
    # consider it a duplicate and remove the second spike.
    for unit_id in sorting.get_unit_ids():
        spike_train = sorting.get_unit_spike_train(unit_id=unit_id)     # Contains the time at which all spikes where captured (in timepoints).
        time_diff_spikes = np.diff(spike_train)                         # At index i, contains the time difference between spikes i and spike i+1.
        duplicates = np.where(time_diff_spikes < window_duplicate)[0]+1 # Contains the indices of the second spike (the one to remove).

        # Remove the duplicated spikes from the spike trains.
        sorting = del_spikes_from_unit(sorting, duplicates, unit_id)


    return sorting
```

In `curation/utils/sorting_utils.py`:
```
import numpy as np
import spikeextractors as se
import spiketoolkit as st



def del_spikes_from_unit(sorting, spikes, unit_id):
    """
    Removes spikes based on their index in a certain unit.
    sorting = any Sorting from spikeinterface containing the data
    spikes = list of all indices of spikes to delete
    unid_id = ID of the unit containing the spikes to delete
    """

    if not isinstance(sorting, se.SortingExtractor):
        print("Error in del_spikes_from_unit():")
        print("parameter 'sorting' must be an instance of spikeextractors.SortingExtractor")
        print("Current 'sorting' is an instance of '{0}'".format(type(sorting)))
        return
    if not isinstance(spikes, list) and not isinstance(spikes, np.ndarray):
        print("Error in del_spikes_from_unit():")
        print("parameter 'spikes' must be an instance of list or numpy.ndarray")
        print("Current 'spikes' is an instance of '{0}'".format(type(spikes)))
        return

    if not isinstance(sorting, st.curation.CurationSortingExtractor):
        print("Converting sorting...")
        sorting = st.curation.CurationSortingExtractor(sorting)

    # Need to find the Unit in "roots" that matches our unit_id
    unit = "error"
    for root in sorting._roots:
        if root.unit_id == unit_id:
            unit = root
            break

    if unit == "error": # Didn't find the Unit with our unit_id
        print("Error in del_spikes_from_unit():")
        print("Unit ID {0} not found".format(unit_id))
        return

    spike_train = unit.get_spike_train()
    spike_train = np.delete(spike_train, spikes)
    unit.set_spike_train(spike_train)

    return sorting
```

**Comment by alejoe91** [comment]
As you suggested, I think that the problem is the following: when you set a new spike train for a unit, the features are not reset. Can you look into the [`split_unit`](https://github.com/SpikeInterface/spiketoolkit/blob/ad3b1e2a64beef66547bd3b74852a5e1e712b93d/spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py#L191) method instead? That should take care of it

**Comment by Dradeliomecus** [comment]
Setting `recompute_info = True` solved the problem.

Using `split_unit` with `recompute_info = False` also worked!
Thank you.

Is it possible to have the method `split_unit()` return a tuple containing the 2 unit_ids of the new units ? That way it would be easy to remove one of them.

**Comment by alejoe91** [comment]
I think that should be possible :) @colehurwitz can you take care of this?

**Comment by colehurwitz** [comment]
Yes, I can do that.

**Comment by alejoe91** [comment]
@colehurwitz we should also add a dump mechanism for the curator extractor

**Comment by alejoe91** [comment]
Fixed
