### ISSUE TITLE
TypeError: set_unit_spike_features() got an unexpected keyword argument 'indexes'

### ISSUE THREAD

**Issue by MingChingChiang** [SpikeInterface/spiketoolkit#363]
Hi,
When I try to export my sorted file to phy, I got the same error message when executing this code:
sorting_MS4 = ss.run_mountainsort4(recording=recording, **default_ms4_params, grouping_property='group', output_folder=OUT_MS4, verbose=True)

My error messages are:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 5, in
output_folder=MS4_Phy, verbose=True)
File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 984, in export_to_phy
max_channels_per_template, **kwargs)
File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1412, in _get_phy_data
seed=seed, compute_pc_features=compute_pc_features)
File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1232, in _get_quality_metric_data
max_channels_per_waveforms)
File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 288, in get_unit_waveforms
sorting.set_unit_spike_features(unit_id, 'waveforms', waveform_list[i], indexes=spike_index_list[i])
TypeError: set_unit_spike_features() got an unexpected keyword argument 'indexes'

I've updated to the latest version of spiketoolkit and spikesorters, but don't know how to fix the problem.

Is it possible that because of the grouping properties, since I previously have successfully exported the ungrouped data to phy-readable format.

**Comment by alejoe91** [comment]
Hi! Did you update also to the latest version of spikeextractors? The problem seems related to it. I don't think it's because of grouping, as we have specific tests for it

**Comment by MingChingChiang** [comment]
> Hi! Did you update also to the latest version of spikeextractors? The problem seems related to it. I don't think it's because of grouping, as we have specific tests for it

I see! I will update the spikeextractors, so far I only update the spiketoolkit and spikesorters.

**Comment by MingChingChiang** [comment]
> Hi! Did you update also to the latest version of spikeextractors? The problem seems related to it. I don't think it's because of grouping, as we have specific tests for it

I've updated the spikeextractors to version 0.8.2 and rerun the export_to_phy. 
However, I got another error message:
Fitting PCA of 3 dimensions on 10000 waveforms
Projecting waveforms on PC
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3688bad0d18f>", line 5, in <module>
    grouping_property='group', verbose=True)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 984, in export_to_phy
    max_channels_per_template, **kwargs)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1454, in _get_phy_data
    templates_red[u_i, :] = templates[u_i, :, unit_chans].T
IndexError: index 16 is out of bounds for axis 2 with size 16

I've noticed that there is a similar issue #342 [https://github.com/SpikeInterface/spiketoolkit/issues/342#issue-604349128](url) which you've closed. 

So I think I need to provide more information.
Now the versions of each library are: 
spikecomparison               0.2.3       
spikeextractors                  0.8.2       
spikeinterface                    0.9.1       
spikemetrics                       0.1.4       
spikesorters                       0.3.0       
spiketoolkit                         0.6.1       
spikewidgets                      0.4.1       

Here are my codes for spikesorting (jupyter notebook): 
[https://drive.google.com/file/d/1fLArIL9LH9gy3AUqta2bvALj88Ecerji/view?usp=sharing](url)

The Recording Data, as well as the probe file, could be found here:
[https://drive.google.com/open?id=1boUFsKuuhABukD9wUusTOnsbtex8xOWW](url)

Hope you can help me to figure out how to fix my problem.
Thank you very much!

**Comment by alejoe91** [comment]
Hi @MingChingChiang 

Thanks for the info! Can you try to install spiketoolkit from sources? 
I think that that fix is not in the release, but I'll make a new release of all packages today!

**Comment by MingChingChiang** [comment]
> Hi @MingChingChiang
> 
> Thanks for the info! Can you try to install spiketoolkit from sources?
> I think that that fix is not in the release, but I'll make a new release of all packages today!

Sure! I will install the spiketoolkit from sources and run the codes again!
Thanks for helping out!

**Comment by MingChingChiang** [comment]
Hi @alejoe91 
I've used the latest spiketoolkit, spikeextractor, and spikesorters for spike sorting, but I still have the same problem during phy export. (I just reinstall everything 4 hours ago)
The error messages I got were:
Fitting PCA of 3 dimensions on 10000 waveforms
Projecting waveforms on PC
Traceback (most recent call last):
  File "/Users/Ming-Ching/Documents/Python_Project/Spike_Sorting/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-fd3e386ce03d>", line 6, in <module>
    output_folder=MS4_Phy, verbose=True)
  File "/Users/Ming-Ching/Documents/Python_Project/Spike_Sorting/venv/lib/python3.7/site-packages/spiketoolkit-0.6.2-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1088, in export_to_phy
    max_channels_per_template, **kwargs)
  File "/Users/Ming-Ching/Documents/Python_Project/Spike_Sorting/venv/lib/python3.7/site-packages/spiketoolkit-0.6.2-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1559, in _get_phy_data
    templates_red[u_i, :] = templates[u_i, :, unit_chans].T
IndexError: index 16 is out of bounds for axis 2 with size 16

The versions of those packages are:
spikecomparison            0.2.4
spikeextractors               0.8.3
spikefeatures                  0.1.0
spikeinterface                 0.9.1 
spikemetrics                   0.2.0
spikesorters                    0.3.1
spiketoolkit                     0.6.2
spikewidgets                  0.4.2

Please let me know how to fix my problem if you have any new ideas or solutions, thanks!

**Comment by alejoe91** [comment]
Hi @MingChingChiang 

Found the same bug. It happens when you have more channels than `max_channels_per_template` and you use the `grouping_property`. A quick fix for now is passing the `max_channels_per_template=None` argument to the `export_to_phy`. 
Fixing it properly now :)

**Comment by alejoe91** [comment]
Fixed here: https://github.com/SpikeInterface/spiketoolkit/pull/364

Basically when exporting by group the `max_channels_per_template` is ignored

**Comment by MingChingChiang** [comment]
> Fixed here: #364
> 
> Basically when exporting by group the `max_channels_per_template` is ignored

I've tried this solution, and the sorters and the phy export just worked perfectly!
Thanks a lot!
