### ISSUE TITLE
Memory error during postprocessing.export_to_phy

### ISSUE THREAD

**Issue by jdacre** [SpikeInterface/spiketoolkit#372]
Hi,

I am trying to use the code below to use Ironclust to spike sort one of Adam Kampff's neuropixel recordings (6.2GB file size, 384 channels, 8100337 samples long)

```
import spikeextractors as se
import spiketoolkit as st
import spikesorters as ss
file_path = '/home/jdacre/duguidlab/thalamus_paper/Npx_data/raw/Kampff_C1/c1_npx_raw.imec0.ap.bin'
recording = se.SpikeGLXRecordingExtractor(file_path=file_path)
ic_params = ss.get_default_params('ironclust')
sorting_ic = ss.run_ironclust(recording=recording, **ic_params)
out_path = '/home/jdacre/duguidlab/thalamus_paper/Npx_data/processed/Kampff_C1/'
st.postprocessing.export_to_phy(recording, sorting_ic, output_folder=out_path, verbose=True, max_spikes_per_unit=10000)
```
but receive a memory error with running `postprocessing.export_to_phy`:

```
Waveform 1/110
Traceback (most recent call last):
  File "/home/jdacre/.local/share/umake/ide/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jdacre/.local/share/umake/ide/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jdacre/duguidlab/shared_lab_resources/Neuropixels/pixels-analysis/projects/JD/run_single_sorter.py", line 80, in <module>
    st.postprocessing.export_to_phy(recording, sorting_ic, output_folder=out_path, verbose=True, max_spikes_per_unit=10000)
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1143, in export_to_phy
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1603, in _get_phy_data
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1399, in _get_quality_metric_data
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 176, in get_unit_waveforms
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1854, in _extract_waveforms_one_unit
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spiketoolkit-0.6.3-py3.6.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1225, in _get_random_spike_waveforms
  File "/opt/anaconda3/envs/pixels/lib/python3.6/site-packages/spikeextractors-0.8.4-py3.6.egg/spikeextractors/recordingextractor.py", line 191, in get_snippets
MemoryError: Unable to allocate 236. GiB for an array with shape (1834449, 384, 180) and data type int16

Process finished with exit code 1
```
I'm using st.__version__ '0.6.3' and se.__version__ '0.8.4'. Any ideas as to why this is happening?

**Comment by alejoe91** [comment]
HI @jdacre 

I think something went wrong with that first unit from IC! The length of the spike train is almost 2 million, and the duration is less than 5 minutes. `spiketoolkit` tries to save the waveforms to a file. Now, each waveform has 180 time samples (you can decrease thos using the `ms_before`-`ms_after` args) times 384 channels times 2 million ~ 236 Gb.

Since this is happening with the first unit, you can try to filter it out in 2 ways:

1. Use the `SubSortingExtractor`:

```
sorting_ic_new = se.SubSortingExtractor(sorting_ic, unit_ids=sorting_ic.get_unit_ids()[1:])
```

2. Using the `spiketoolkit.curation` module (this will remove all units with this problem, if more than one):

```
max_spikes_per_st = 500000  # you can adjust this or use the same mechanism for the firing rate
# this removes all spike trains with more than ('greater') max_spikes_per_st
sorting_ic_new = st.curation.threshold_num_spikes(sorting_ic, max_spikes_per_st, 'greater')
```

Let me know if it works!

Cheers
Alessio

**Comment by jdacre** [comment]
Hi Alessio,

Thank you very much for those suggestions, chose option 2 and we've gotten past that memory issue, so that was great!
However, it has been running the 
`st.postprocessing.export_to_phy(recording, sorting_ic, output_folder=out_path, verbose=True, max_spikes_per_unit=10000)
`
step for ~16 hours so far and has only processed 53/109 waveforms so far, compared to the rest of the spike sorting processes which were done within ~20 mins on this data. Does that sound as expected to you?

**Comment by alejoe91** [comment]
Hi,

By default only one job is used, and clearly this is not suitable for Neurpixels data. You can add joblib parallel processing by using the `n_jobs` argument (of course, the more the better).

Also note that the processing time is so large because in order to compute pc features, ALL waveforms need to be extracted (the `max_spikes_per_unit=10000` is ignored in this case). The same goes for amplitudes. 
You can avoid to compute pc scores by setting the `compute_pc_features=False` and to compute amplitudes with the `compute_amplitudes=False`. When `compute_pc_features=False`, the `max_spikes_per_unit` is not ignored anymore, and you can get a good template also with less than 10000 spikes per unit (1000 should work well). 
You will still get a good visualization of the templates, similarity scores, correlograms, ISI distributions etc. in Phy.

**Comment by jdacre** [comment]
Thanks again alejoe, that should sort us!

**Comment by jdacre** [comment]
Yes, successfully exported to phy, thank you

**Comment by alejoe91** [comment]
Great!
