### ISSUE TITLE
Impossible to delete temp file

### ISSUE THREAD

**Issue by TRuikes** [SpikeInterface/spiketoolkit#391]
When running `st.validation.compute_quality_metrics` with `memmap=True`, I'll get 'Impossible to delete temp file' warning. As a result the Temp folder becomes huge.

**Comment by alejoe91** [comment]
Hi @TRuikes 

Yeah Windows complains because the memmap files are still open when you try to delete them. You get a `PermissionError`, right? The solution would be to add a proper `__del__` method to the memmap objects that belong to an extractor. I'll give it a try and ask you to try out a PR (for spikeextractors) once that's done. Ok?

**Comment by alejoe91** [comment]
@TRuikes 

Can you try this spikeextractors PR https://github.com/SpikeInterface/spikeextractors/pull/450 ?

**Comment by TRuikes** [comment]
Sorry I didn't paste the whole error string. But probably a permission error:
`Impossible to delete temp file: C:\Users\truikes\AppData\Local\Temp\tmppnrzgloz Error [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\truikes\\AppData\\Local\\Temp\\tmppnrzgloz\\amplitudes_0.raw'`

I usually get this if I do not close an openened fill in program A and then try to save/delete with program B. I'll try the fix later today.

**Comment by alejoe91** [comment]
Exactly I think that spikeextractors PR should fix it :)

**Comment by alejoe91** [comment]
@TRuikes can you try again with the latest masters of spikeextractors and spiketoolkit?

**Comment by TRuikes** [comment]
Hi @alejoe91, thanks for the reminder, I'll test it soon (next week probably). Congrats on the paper =).

**Comment by alejoe91** [comment]
Thanks :)

**Comment by TRuikes** [comment]
@alejoe91 I think the warning is still there. I've just created an environment with python 3.7 and installed spiketoolkit and spikeextractors from their master branches and run this code:

```python
import sys
import spiketoolkit as st
import spikeextractors as se
import warnings
import logging

print(st.__version__)
print(se.__version__)


warnings.simplefilter('error')
log = logging.getLogger('my.module.logger')
path = r'D:\Data_julien\Test_klusta\TT_Hpc2'

sort = se.KlustaSortingExtractor(path)
rec = se.KlustaRecordingExtractor(path)

uids = [uid for uid in sort.get_unit_ids()
        if sort.get_unit_property(uid, 'quality') in ['good']]

to_compute = st.validation.get_quality_metrics_list()
res = st.validation.compute_quality_metrics(
    sorting=sort,
    recording=rec,
    unit_ids=[uids[0]],
    memmap=True,
    verbose=True,
    # metric_names=['firing_rate']
)

print(sys.exc_info())
```
which gives me the following output:
```shell
C:\ProgramData\Miniconda3\envs\spikeinterface\python.exe C:/Code/spikeextractors/test_spikeinterface.py
0.7.2
0.9.3
Exception ignored in: <_io.FileIO name=3 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.BufferedRandom name=3>
Computing waveforms
Number of chunks: 4 - Number of jobs: 1
Warning: dumping a CacheRecordingExtractor. The path to the tmp binary file will be lost in further sessions. To prevent this, use the 'CacheRecordingExtractor.move_to('path-to-file)' function
Extracting waveforms in chunks:   0%|          | 0/4 [00:00<?, ?it/s]Warning: dumping a CacheRecordingExtractor. The path to the tmp binary file will be lost in further sessions. To prevent this, use the 'CacheRecordingExtractor.move_to('path-to-file)' function
Warning: dumping a CacheRecordingExtractor. The path to the tmp binary file will be lost in further sessions. To prevent this, use the 'CacheRecordingExtractor.move_to('path-to-file)' function
Warning: dumping a CacheRecordingExtractor. The path to the tmp binary file will be lost in further sessions. To prevent this, use the 'CacheRecordingExtractor.move_to('path-to-file)' function
Extracting waveforms in chunks: 100%|##########| 4/4 [00:00<00:00, 32.33it/s]
Warning: dumping a CacheRecordingExtractor. The path to the tmp binary file will be lost in further sessions. To prevent this, use the 'CacheRecordingExtractor.move_to('path-to-file)' function
Fitting PCA of 3 dimensions on 10000 waveforms
Projecting waveforms on PC
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 100% 
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 100% 
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 100% 
 ▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 9% (None, None, None)
Impossible to delete temp file: C:\Users\truikes\AppData\Local\Temp\tmprpd5uti5 Error [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\truikes\\AppData\\Local\\Temp\\tmprpd5uti5\\all_waveforms.raw'
```

this warning does not arise when calling the function compute only 'firing_rate'

also, is this method supposed to delete the complete temporary folder?

**Comment by alejoe91** [comment]
Hi @TRuikes 
Thanks for testing. I'll dig more into it. 
The should only delete the tmp files (not the tmp folder associated to the sorting extractor) once they are out of scope. 
Moreover, the destructor should delete the tmp folder as well.
Apparently the `all_waveforms` object is still in use when we try to delete the file.

See here: https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/baseextractor.py#L32-L67

You are using the latest version of spikeextractors, right? Version 0.9.3

**Comment by TRuikes** [comment]
yes, to be sure I printed out the version in the script above.

Since it is not happening when only computing firing rate, but is when doing for instance l-ratio, I thought it could be something PCA related (on the waveforms).

**Comment by alejoe91** [comment]
Does it happen when you compute snr? Snr computes waveforms but not PCA, so we can see if it's a problem of waveforms min general or pca computation.

**Comment by TRuikes** [comment]
its also happening with snr indeed

**Comment by alejoe91** [comment]
Can you try to see where exactly it's throwing the warning? Maybe by adding some print statements in the code part that I sent you

**Comment by TRuikes** [comment]
I tried a few things, but it's not superclear what function is trying to close the file. Adding this to `del_memmap_file`:
```python
        print(memmap_file)
        if os.path.isfile(memmap_file):
            os.unlink(memmap_file)
```
yielded just before the crash:

```
C:/Users/truikes/AppData/Local/Temp/tmp_kw0uq_7/waveforms_0.raw
Exception ignored in: <function BaseExtractor.__del__ at 0x000001A872997E58>
Traceback (most recent call last):
  File "C:\Code\spikeextractors\spikeextractors\baseextractor.py", line 36, in __del__
  File "C:\Code\spikeextractors\spikeextractors\baseextractor.py", line 61, in del_memmap_file
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/truikes/AppData/Local/Temp/tmp_kw0uq_7/waveforms_0.raw'
```

**Comment by alejoe91** [comment]
Ok, we'll need to look more into it. I tried to fix it a few weeks ago, but it's unclear which process is using the file. In the meanwhile, if you files are not huge, you can use `memmap=False as argument and that would compute everything in memory

**Comment by TRuikes** [comment]
the files are pretty big indeed so this function is really usefull. We can manually delete our tmp folder occasionally for now.

**Comment by alejoe91** [comment]
ok! Just to be clear, the error doesn't stop the code from running, but it doesn't delete the temp files, is that right?

**Comment by TRuikes** [comment]
yes!

**Comment by alejoe91** [comment]
Great! We'll try to fix it in the meanwhile then. If you also find a solution, don't hesitate to open a PR to discuss it!

**Comment by TRuikes** [comment]
will do
