### ISSUE TITLE
Dimension issue in spiketoolkit

### ISSUE THREAD

**Issue by Levi55555** [SpikeInterface/spiketoolkit#436]
Hi I have tried to run a python script on our KS data, but I got the following error:

balazsi@BL-ThinkPad:/media/balazsi/Levi-HDD/TTK recordings/ARat_2017_09_11_128ch_probe_PD_170911_132447$ python3 Spikeinterface.py 
Traceback (most recent call last):
  File "Spikeinterface.py", line 18, in <module>
    metrics_df = st.validation.compute_quality_metrics(sorting, recording, metric_names=available_metrics, as_dataframe=True)
  File "/home/balazsi/.local/lib/python3.6/site-packages/spiketoolkit/validation/quality_metrics.py", line 1220, in compute_quality_metrics
    md.compute_amplitudes(**kwargs)
  File "/home/balazsi/.local/lib/python3.6/site-packages/spiketoolkit/validation/quality_metric_classes/metric_data.py", line 186, in compute_amplitudes
    self._recording, self._sorting, **kwargs)
  File "/home/balazsi/.local/lib/python3.6/site-packages/spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py", line 157, in get_amplitude_metric_data
    spike_clusters_amp, amplitudes = _get_amp_metric_data(recording, sorting, **kwargs)
  File "/home/balazsi/.local/lib/python3.6/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 1496, in _get_amp_metric_data
    amplitudes[i_start_amp:i_start_amp + len(st_amp)] = amp[:, np.newaxis]
ValueError: could not broadcast input array from shape (4853,1,1) into shape (4853,1)

I cloned the code from github and installed the tools today.

**Comment by alejoe91** [comment]
Hi @Levi55555 can you share the script?

**Comment by Levi55555** [comment]
import spikeextractors as se
from spikeextractors import KiloSortSortingExtractor, KiloSortRecordingExtractor
from spikeextractors.extractors.phyextractors import PhyRecordingExtractor, PhySortingExtractor
import spiketoolkit as st

# instantiate SI extractors
#recording = se.KiloSortRecordingExtractor('ARat')
recording = KiloSortRecordingExtractor('ARat_2017_09_11_128ch_probe_PD_170911_132447')
sorting = se.KiloSortSortingExtractor('ARat_2017_09_11_128ch_probe_PD_170911_132447')
# if the recording is not filtered, you'll need to filter it
recording = st.preprocessing.bandpass_filter(recording)
# compute waveforms (I would re-do it in spikeinterface for reproducibility + you'll need them for metrics)
waveforms = st.postprocessing.get_unit_waveforms(recording, sorting, max_spikes_per_unit=1000, chunk_mb=2000, n_jobs=8)
# this will use 2 Gb of RAM when processing and split the computation in 8 jobs
# now compute metrics:
available_metrics = st.validation.get_quality_metrics_list()
# you can choose a subset of metrics among the list
metrics_df = st.validation.compute_quality_metrics(sorting, recording, metric_names=available_metrics, as_dataframe=True)
metrics_df.to_csv("result.csv")

**Comment by Levi55555** [comment]
oh sorry for the format...

**Comment by alejoe91** [comment]
What is the output of pip list?

**Comment by Levi55555** [comment]
these could be insteresting:

setuptools (51.1.1)
six (1.15.0)
smmap (3.0.4)
spikecomparison (0.3.1)
spikeextractors (0.9.3)
spikefeatures (0.1.1)
spikemetrics (0.2.2)
spikesorters (0.4.3)
spiketoolkit (0.7.2)
system-service (0.3)
systemd-python (234)
tensorboard (1.14.0)
tensorflow (1.14.0)

**Comment by alejoe91** [comment]
So this was fixed in the master branch, so you need to first pip uninstall spikeextractors and then python setup.py install from inside the spikeextractors repo. Have you done that?

**Comment by Levi55555** [comment]
Yes, you are right, it has solved the problem, but now i got this:

/home/balazsi/.local/lib/python3.6/site-packages/spikemetrics/utils.py:411: RuntimeWarning: invalid value encountered in true_divide
  com = np.array([np.sum((channel_locations[spike_feat_ind][:, :, 0] * pc_power), 1) / np.sum(pc_power, 1),
/home/balazsi/.local/lib/python3.6/site-packages/spikemetrics/utils.py:412: RuntimeWarning: invalid value encountered in true_divide
  np.sum((channel_locations[spike_feat_ind][:, :, 1] * pc_power), 1) / np.sum(pc_power, 1)]).T
Traceback (most recent call last):
  File "Spikeinterface.py", line 18, in <module>
    metrics_df = st.validation.compute_quality_metrics(sorting, recording, metric_names=available_metrics, as_dataframe=True)
  File "/usr/local/lib/python3.6/dist-packages/spiketoolkit-0.7.2-py3.6.egg/spiketoolkit/validation/quality_metrics.py", line 1267, in compute_quality_metrics
  File "/usr/local/lib/python3.6/dist-packages/spiketoolkit-0.7.2-py3.6.egg/spiketoolkit/validation/quality_metric_classes/silhouette_score.py", line 35, in compute_metric
  File "/home/balazsi/.local/lib/python3.6/site-packages/spikemetrics/metrics.py", line 426, in calculate_silhouette_score
    SS[i, j] = silhouette_score(X, labels, random_state=seed)
  File "/home/balazsi/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/balazsi/.local/lib/python3.6/site-packages/sklearn/metrics/cluster/_unsupervised.py", line 117, in silhouette_score
    return np.mean(silhouette_samples(X, labels, metric=metric, **kwds))
  File "/home/balazsi/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/balazsi/.local/lib/python3.6/site-packages/sklearn/metrics/cluster/_unsupervised.py", line 229, in silhouette_samples
    check_number_of_labels(len(le.classes_), n_samples)
  File "/home/balazsi/.local/lib/python3.6/site-packages/sklearn/metrics/cluster/_unsupervised.py", line 35, in check_number_of_labels
    "to n_samples - 1 (inclusive)" % n_labels)
ValueError: Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)

**Comment by alejoe91** [comment]
How many units do you have?

**Comment by Levi55555** [comment]
The number of all units is 475.

**Comment by Levi55555** [comment]
Hi!
Here you can find the KS data folder if it helps:
https://ttkmtahu-my.sharepoint.com/personal/meszena_domokos_ttk_mta_hu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmeszena%5Fdomokos%5Fttk%5Fmta%5Fhu%2FDocuments%2FPublic%5Fmegosztasi%2Fdata%2FARat%5F2017%5F09%5F11%5F128ch%5Fprobe%5FPD%5F170911%5F132447&originalPath=aHR0cHM6Ly90dGttdGFodS1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9tZXN6ZW5hX2RvbW9rb3NfdHRrX210YV9odS9FcXA0LXhJY2RkWkhwS20yOFZ4OG1HRUIzNGRrNURORmR2ZGNwcUJCQkhtUENnP3J0aW1lPUpuYVFUVEM5MkVn

**Comment by alejoe91** [comment]
Thanks @Levi55555 

It seems I can't access the data. Maybe send me an email and we can figure out a good way to share the data.

Cheers
Alessio
