### ISSUE TITLE
NWB-related error with read from nwb recording extractor

### ISSUE THREAD

**Issue by lfrank** [SpikeInterface/spiketoolkit#486]
We have a recording extractor that we've written to an NWB file, and when we try to use it to compute metrics, we get the error below. 

Note that I've modified my local version of the nwb extractor to include load_namespaces=True, and I was planning to submit a pull request once we tested it.

any thoughts on this?

> --------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 1998, in _extract_waveforms_one_chunk
    recording = se.load_extractor_from_dict(rec_arg)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/extraction_tools.py", line 732, in load_extractor_from_dict
    return BaseExtractor.load_extractor_from_dict(d)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 523, in load_extractor_from_dict
    extractor = _load_extractor_from_dict(d)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 554, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 554, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 554, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  [Previous line repeated 3 more times]
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 585, in _load_extractor_from_dict
    extractor = cls(**kwargs)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/extractors/nwbextractors/nwbextractors.py", line 188, in __init__
    nwbfile = io.read()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/backends/hdf5/h5tools.py", line 495, in read
    return call_docval_func(super().read, kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 423, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/backends/io.py", line 41, in read
    container = self.__manager.construct(f_builder)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 280, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 790, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1194, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1194, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1186, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1199, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1199, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 785, in construct
    obj_mapper = self.get_map(builder)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 704, in get_map
    container_cls = self.get_cls(obj)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 637, in get_cls
    return self.get_dt_container_cls(data_type, namespace)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 523, in get_dt_container_cls
    self.__check_dependent_types(spec, namespace)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 549, in __check_dependent_types
    __check_dependent_types_helper(child_spec, namespace)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 536, in __check_dependent_types_helper
    self.get_dt_container_cls(spec.data_type_inc, namespace)  # TODO handle recursive definitions
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/manager.py", line 526, in get_dt_container_cls
    cls = self.__class_generator.generate_class(data_type, spec, parent_cls, attr_names, self)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 580, in func_call
    return func(args[0], **pargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/build/classgenerator.py", line 84, in generate_class
    cls = ExtenderMeta(data_type, tuple(bases), classdict)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/utils.py", line 755, in __init__
    func(name, bases, classdict)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/hdmf/container.py", line 132, in __gather_fields
    raise TypeError(msg)
TypeError: '__nwbfields__' must be of type tuple
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-39-7e09ac06513c> in <module>
      1 # Specify entry (otherwise runs everything in SpikeSortingParameters)
      2 # `proj` gives you primary key
----> 3 SpikeSorting.populate([(SpikeSortingParameters & {'nwb_file_name' : nwb_file_name}).proj()])

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/datajoint/autopopulate.py in populate(self, suppress_errors, return_exception_objects, reserve_jobs, order, limit, max_calls, display_progress, *restrictions)
    151                     self.__class__._allow_insert = True
    152                     try:
--> 153                         make(dict(key))
    154                     except (KeyboardInterrupt, SystemExit, Exception) as error:
    155                         try:

~/Src/NWB/nwb_datajoint/src/nwb_datajoint/common/common_spikesorting.py in make(self, key)
    581         with Timer(label='compute metrics', verbose=True):
    582             metrics_key = (SpikeSortingParameters & key).fetch1('cluster_metrics_list_name')
--> 583             metrics = SpikeSortingMetrics().compute_metrics(metrics_key, recording, sorting)
    584 
    585         print('\nSaving sorting results...')

~/Src/NWB/nwb_datajoint/src/nwb_datajoint/common/common_spikesorting.py in compute_metrics(self, key, recording, sorting)
    382         m = (self & {'cluster_metrics_list_name': key}).fetch(as_dict=True)[0]
    383 
--> 384         return st.validation.compute_quality_metrics(sorting=sorting,
    385                                                      recording=recording,
    386                                                      metric_names=self.selected_metrics_list(m['metric_dict']),

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/validation/quality_metrics.py in compute_quality_metrics(sorting, recording, duration_in_frames, sampling_frequency, metric_names, unit_ids, as_dataframe, isi_threshold, min_isi, snr_mode, snr_noise_duration, max_spikes_per_unit_for_snr, template_mode, max_channel_peak, max_spikes_per_unit_for_noise_overlap, noise_overlap_num_features, noise_overlap_num_knn, drift_metrics_interval_s, drift_metrics_min_spikes_per_interval, max_spikes_for_silhouette, num_channels_to_compare, max_spikes_per_cluster, max_spikes_for_nn, n_neighbors, **kwargs)
   1214                              "silhouette_score isolation_distance, l_ratio, d_prime, nn_hit_rate, or amplitude_cutoff.")
   1215         else:
-> 1216             md.compute_pca_scores(**kwargs)
   1217 
   1218     if "amplitude_cutoff" in metric_names:

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/validation/quality_metric_classes/metric_data.py in compute_pca_scores(self, **kwargs)
    222 
    223         spike_times, spike_times_pca, spike_clusters, spike_clusters_pca, pc_features, \
--> 224         pc_feature_ind = get_pca_metric_data(self._recording, self._sorting, **kwargs)
    225         self._pc_features = pc_features
    226         self._spike_clusters_pca = spike_clusters

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py in get_pca_metric_data(recording, sorting, **kwargs)
     99 
    100     spike_times, spike_times_pca, spike_clusters, \
--> 101     spike_clusters_pca, pc_features, pc_feature_ind = _get_pca_metric_data(recording, sorting, **kwargs)
    102 
    103     return np.squeeze(recording.frame_to_time(spike_times)), np.squeeze(recording.frame_to_time(spike_times_pca)),\

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in _get_pca_metric_data(recording, sorting, **kwargs)
   1550         sorting.clear_units_spike_features(feature_name='waveforms')
   1551 
-> 1552     pc_list, pca_idxs, pc_ind = compute_unit_pca_scores(recording, sorting, return_idxs=True, **kwargs)
   1553 
   1554     # compute len of all waveforms (computed for all units)

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in compute_unit_pca_scores(recording, sorting, unit_ids, channel_ids, return_idxs, _waveforms, _spike_index_list, _channel_index_list, **kwargs)
   1061             if verbose:
   1062                 print("Computing waveforms")
-> 1063             waveforms, spike_index_list, channel_index_list = get_unit_waveforms(recording, sorting, unit_ids,
   1064                                                                                  channel_ids,
   1065                                                                                  return_idxs=True, **kwargs)

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_waveforms(recording, sorting, unit_ids, channel_ids, return_idxs, chunk_size, chunk_mb, **kwargs)
    267         else:
    268             # waveforms are saved directly to the memmap file if
--> 269             unit_waveforms = Parallel(n_jobs=n_jobs, backend=joblib_backend)(
    270                 delayed(_extract_waveforms_one_chunk)(ii, rec_arg, chunks, unit_ids, n_pad,
    271                                                       times_in_all_chunks, start_spike_idxs,

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/anaconda3/envs/nwb_datajoint/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~/anaconda3/envs/nwb_datajoint/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

TypeError: '__nwbfields__' must be of type tuple

**Comment by rly** [comment]
I am now able to reproduce the error, and I am working on a fix. It is a bug on the PyNWB/HDMF side for generating API classes (e.g., when a file with the ndx-franklab-novela extension is read but ndx-franklab-novela is not imported).

**Comment by rly** [comment]
HDMF 2.5.7 (just released) should fix this error. However, if the file contains an `ndx_franklab_novela.NwbImageSeries`, and that object lacks a 'data' dataset, there may be a different error.

Please retry this and let me know how it goes.
